### ISSUE TITLE
You mean I don’t have to summon Malloc with capital letters EXTRA_EXPORTED_RUNTIME_FUNCTION???

### ISSUE THREAD

**Issue by yishengjiang99** [maxkl/wasm-malloc#4]

**Comment by maxkl** [comment]
I'm not sure what you mean. If you haven't been able to find an answer/solve your problem yet, could you please clarify?

**Comment by yishengjiang99** [comment]
i was just mock how emscripten requires you to type every exported function in capital letters if you want to use itl
